refresh_rate: 30 seconds

appenders:
  file:
    kind: file
    path: log.txt
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | Thr: {t} | Mod: {M} | {({l}):5.5} | {f}:{L} — {m}{n}"
root:
  level: trace
  appenders:
    - file
